base_url = "https://lethalbit.net"
title = "cat /dev/aki"
description = "Various ramblings from Aki"

default_language = "en"
compile_sass = true

build_search_index = false
taxonomies = [
    { name = "topics", rss = true, paginate_by = 10 },
    { name = "tags", rss = true, paginate_by = 10 },
]
generate_feeds = true

author = "Aki"

[extra]
author = "Aki"

menus = [
    {url = "https://github.com/lethalbit", name = "Github"},
    {url = "https://twitter.com/lethalbit", name = "Twitter"},
    {url = "https://chaos.social/@lethalbit", name = "Mastodon"},
]

[markdown]
highlight_code = true
external_links_target_blank = true
bottom_footnotes = true

[link_checker]
internal_level = "error"
external_level = "error"
