base_url = "https://lethalbit.net"
title = "cat /dev/aki"
description = "Various ramblings from Aki"
sort_by = "date"
default_language = "en"
compile_sass = true

build_search_index = false
paginate_by = 5
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]
generate_feed = true
[extra]
author = "Aki"

menus = [
    {url = "https://github.com/lethalbit", name = "Github"},
    {url = "https://twitter.com/lethalbit", name = "Twitter"},
    {url = "https://chaos.social/@lethalbit", name = "Mastodon"},
]

[markdown]
highlight_code = true
external_links_target_blank = true
